#!/bin/bash
PLUGIN_DOR="pack/vendor/opt"
PACK_NAME="vimcdoc"
git submodule add https://github.com/yianwillis/vimcdoc.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add VimCdoc."
PACK_NAME="vim-airline-themes"
git submodule add https://github.com/vim-airline/vim-airline-themes.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add VimAirlineThemes."
PACK_NAME="vim-airline"
git submodule add https://github.com/vim-airline/vim-airline.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add VimAirline."
PACK_NAME="indentLine"
git submodule add https://github.com/Yggdroot/indentLine.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add IndentLine."
PACK_NAME="vim-rainbow"
git submodule add https://github.com/frazrepo/vim-rainbow.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add VimRainbow."
PACK_NAME="vim-surround"
git submodule add https://github.com/tpope/vim-surround.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add VimSurround."
PACK_NAME="Trinity"
git submodule add https://github.com/WeiWangnudt/Trinity.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add Trinity"
PACK_NAME="nerdtree"
git submodule add https://github.com/preservim/nerdtree.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add NERDTree."
PACK_NAME="taglist"
git submodule add https://github.com/vim-scripts/taglist.vim.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add TagList."
PACK_NAME="SrcExpl"
git submodule add https://github.com/vim-scripts/SrcExpl.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add SrcExpl."
PACK_NAME="bufexplorer"
git submodule add https://github.com/vim-scripts/bufexplorer.zip.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add BufExplorer."
PACK_NAME="neocomplcache"
git submodule add https://github.com/Shougo/neocomplcache.vim.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add NeoComplcache."
PACK_NAME="neosnippet-snippets"
git submodule add https://github.com/Shougo/neosnippet-snippets.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add NeoSnippet-snippets."
PACK_NAME="neosnippet"
git submodule add https://github.com/Shougo/neosnippet.vim.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add NeoSnippet."
PACK_NAME="tlib_vim"
git submodule add https://github.com/tomtom/tlib_vim.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add Tlib_vim."
PACK_NAME="vim-addon-mw-utils"
git submodule add https://github.com/MarcWeber/vim-addon-mw-utils.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add VimAddonMwUtils."
PACK_NAME="vim-snippets"
git submodule add https://github.com/honza/vim-snippets.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add VimSnippets."
PACK_NAME=""vim-snipmate
git submodule add https://github.com/garbas/vim-snipmate.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add VimSnipMate."
PACK_NAME="code-templates"
git submodule add https://github.com/WolfgangMehner/vim-plugins.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add CodeTemplates."
PACK_NAME="fugitive"
git submodule add https://github.com/tpope/vim-fugitive.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add fugitive."
PACK_NAME="AnsiEsc"
git submodule add https://github.com/vim-scripts/AnsiEsc.vim.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add AnsiEsc."
PACK_NAME="vim-flog"
git submodule add https://github.com/rbong/vim-flog.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add VimFlog."
PACK_NAME="vim-gitgutter"
git submodule add https://github.com/airblade/vim-gitgutter.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add Gitgutter."
PACK_NAME="git-signify"
git submodule add https://github.com/mhinz/vim-signify.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add GitSignify."
PACK_NAME="omnisharp"
git submodule add https://github.com/OmniSharp/omnisharp-vim.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add OmniSharp."
PACK_NAME="syntastic"
git submodule add https://github.com/vim-syntastic/syntastic.git "$PLUGIN_DOR"/"$PACK_NAME"
git commit -a -m "Add Syntastic."
